#!/bin/bash

source_bash_files() {

    declare -r CURRENT_DIRECTORY="$(pwd)"

    declare -r -a FILES_TO_SOURCE=(
        "bash_alias"
        "bash_exports"
        "bash_functions"
        "bash_options"
        "bash_prompt"

        "bash.local" # local setting
    )

    local file=""
    local i=""

    cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")" \
        && . "../setup/utils.sh"

    for i in ${!FILES_TO_SOURCE[*]}; do

        file="$HOME/.${FILES_TO_SOURCE[$i]}"


        if [ -r "$file" ]; then
            . "$file"
        fi

    done
    cd "$CURRENT_DIRECTORY"
 }

source_bash_files
unset -f source_bash_files

# Clear System message
clear
